apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: fdk-dcat
  name: fdk-dcat
spec:
  selector:
    matchLabels:
      io.kompose.service: fdk-dcat
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        io.kompose.service: fdk-dcat
    spec:
      restartPolicy: Always
      containers:
        - name: fdk-dcat
          image: fintlabs.azurecr.io/fdk-dcat-service:RC-1
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: Europe/Oslo
