apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: fdk-dcat
  name: fdk-dcat
spec:
  selector:
    matchLabels:
      io.kompose.service: fdk-dcat
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        io.kompose.service: fdk-dcat
    spec:
      restartPolicy: Always
      containers:
        - name: fdk-dcat
          image: fintlabs.azurecr.io/fdk-dcat-service:RC-2
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: Europe/Oslo
            - name: fint.ldap.url
              value: ldap://10.0.0.55
            - name: fint.ldap.component-base
              value: ou=components,o=fint
            - name: fint.ldap.contact-base
              value: ou=contacts,o=fint
            - name: fint.ldap.organisation-base
              value: ou=organisations,o=fint
            - name: fint.ldap.user
              valueFrom:
                secretKeyRef:
                  name: fint-portal-user
                  key: ldap.user
            - name: fint.ldap.password
              valueFrom:
                secretKeyRef:
                  name: fint-portal-user
                  key: ldap.password
            - name: fint.nam.oauth.idp-hostname
              value: idp.felleskomponent.no
            - name: fint.nam.oauth.clientId
              valueFrom:
                secretKeyRef:
                  name: fint-portal-user
                  key: nam.oauth.clientId
            - name: fint.nam.oauth.clientSecret
              valueFrom:
                secretKeyRef:
                  name: fint-portal-user
                  key: nam.oauth.clientSecret
            - name: fint.nam.oauth.username
              valueFrom:
                secretKeyRef:
                  name: fint-portal-user
                  key: nam.oauth.username
            - name: fint.nam.oauth.password
              valueFrom:
                secretKeyRef:
                  name: fint-portal-user
                  key: nam.oauth.password
